# Generated by Django 2.2.5 on 2019-10-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20191008_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='do_by_date',
            field=models.DateField(blank=True, null=True, verbose_name='Do-by date'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='child', to='todo.ToDo'),
        ),
    ]
