# Generated by Django 2.2.5 on 2019-10-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20191008_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='todos', to='todo.Tag'),
        ),
    ]
