# Generated by Django 2.2.5 on 2019-10-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20191008_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='tags',
            new_name='tag_list',
        ),
    ]
